CREATE TABLE [dbo].[PlayByPlay] (
    [ProcessExecutionID1] INT           NULL,
    [LoadDateTime1]       DATETIME2 (7) NULL,
    [ProcessExecutionID]  INT           NULL,
    [LoadDateTime]        DATETIME2 (7) NULL,
    [ID]                  VARCHAR (6)   NULL,
    [GameID]              VARCHAR (10)  NULL,
    [CalendarSkey]        VARCHAR (8)   NULL,
    [PasserSkey]          INT           NULL,
    [RusherSkey]          INT           NULL,
    [ReceiverSkey]        INT           NULL,
    [Tackler1Skey]        INT           NULL,
    [Tackler2Skey]        INT           NULL,
    [ReturnerSkey]        INT           NULL,
    [BlockingPlayerSkey]  INT           NULL,
    [PenalizedPlayerSkey] INT           NULL,
    [PassOutcomeSkey]     INT           NULL,
    [ReturnResultSkey]    INT           NULL,
    [OffensiveTeamSkey]   INT           NULL,
    [DefensiveTeamSkey]   INT           NULL,
    [PlayTypeSkey]        INT           NULL,
    [YardsGained]         VARCHAR (3)   NULL,
    [Touchdown]           VARCHAR (1)   NULL,
    [PassAttempt]         VARCHAR (1)   NULL,
    [RushAttempt]         VARCHAR (1)   NULL,
    [Reception]           VARCHAR (1)   NULL,
    [Sack]                VARCHAR (1)   NULL
);

